project_id = "iwutiqervpapcjqfmshd"

[auth]
enabled = true
site_url = "https://next-app-sooty-phi.vercel.app"
additional_redirect_urls = ["https://next-app-sooty-phi.vercel.app/auth/callback", "http://localhost:3000/auth/callback", "http://127.0.0.1:3000/auth/callback"]

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600
